[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[build]
  publish = "_site"
  command = "pnpm prod"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
