[build]
  publish = "public"
  command = "node ./netlify-scripts/create-env.js && yarn build"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
