name: Scheduled Build
on:
  schedule:
  - cron: '30 3 * * *'
jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Trigger Netlify build webhook
    run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
    env:
      TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
